export const FamousPlaceData = [
    {
      coords:[10.7720894,106.6960879],
      id: 1,
      name: 'Bến Thành Market',
      city: 'Hồ Chí Minh city',
      address: 'Chợ, Lê Lợi, Phường Bến Thành, Quận 1, Hồ Chí Minh',
      url:"https://www.itourvn.com/images/easyblog_articles/192/ben-thanh-market.jpg",
      openHours: '7:00 AM - 7:00 PM',
      phone: '0845013684',
      foundationYear: 1859,
      visitors: '220M',
      comments: "30.2K",
      rating: 3.9,
      des:"Bến Thành Market is a large marketplace in central Hồ Chí Minh City, Vietnam in District 1. The market is one of the earliest surviving structures in Saigon and an important symbol of Ho Chi Minh City, popular with tourists seeking local handicrafts, textiles, áo dài and souvenirs, as well as local cuisine."
    },
    {
      coords:[10.7771437,106.6954479],
      id: 2,
      name: 'Independence Palace',
      city: 'Hồ Chí Minh city',
      address: '135 Nam Kỳ Khởi Nghĩa, Phường Bến Thành, Quận 1',
      url:"https://www.itourvn.com/images/easyblog_articles/155/Independence-Palace.jpg",
      openHours: '7:30 – 11:00 AM, 1:00 – 4:00 PM',
      phone: '0845013684',
      foundationYear: 1966,
      visitors: '310M',
      comments: "21.0K",
      rating: 4.4,
      des:"Independence Palace, also known as Reunification Palace, built on the site of the former Norodom Palace, is a landmark in Saigon, Vietnam. It was designed by architect Ngô Viết Thụ and was the home and workplace of the President of South Vietnam during the Vietnam War. It was the site of the end of the Vietnam War during the Fall of Saigon on 30 April 1975, when a North Vietnamese army tank crashed through its gates."
    },
    {
      coords:[10.7797855,106.6990189],
      id: 3,
      name: 'Notre Dame Cathedral of Saigon',
      city: 'Hồ Chí Minh city',
      address: '01 Công xã Paris, Bến Nghé, Quận 1, Hồ Chí Minh',
      url:"http://static.asiawebdirect.com/m/bangkok/portals/vietnam/homepage/ho-chi-minh-city/notre-dame-cathedral/allParagraphs/BucketComponent/ListingContainer/02/BucketList/0/image1/notre-dame-cathedral-04.jpg",
      openHours: '6:00 AM - 4:00 PM',
      phone: '1080',
      foundationYear: 1880,
      visitors: '105M',
      comments: "12.2K",
      rating: 4.4,
      des:"Notre-Dame Cathedral Basilica of Saigon, officially Cathedral Basilica of Our Lady of The Immaculate Conception is a cathedral located in the downtown of Ho Chi Minh City, Vietnam. Established by French colonists who initially named it L'eglise de Saïgon, the cathedral was constructed between 1863 and 1880."
    },
    {
      coords:[10.7794495,106.692418],
      id: 4,
      name: 'War Remnants Museum',
      city: 'Hồ Chí Minh city',
      address: '28 Võ Văn Tần, Phường 6, Quận 3',
      url:"http://static.asiawebdirect.com/m/bangkok/portals/vietnam/homepage/ho-chi-minh-city/war-remnants-museum/pagePropertiesImage/war-remnants-museum-ho-chi-minh.jpg.jpg",
      openHours: '7:30 AM - 6:00 PM',
      phone: "02839305587",
      foundationYear: 1975,
      visitors: '180M',
      comments: "22.0K",
      rating: 4.4,
      des:"The War Remnants Museum is a war museum at 28 Vo Van Tan, in District 3, Ho Chi Minh City, Vietnam. It contains exhibits relating to the Vietnam War and the First Indochina War."
    },
    {
      coords:[10.7798579,106.6999075],
      id: 5,
      name: 'Saigon Central Post Office',
      city: 'Hồ Chí Minh city',
      address: '2 Công xã Paris, Bến Nghé, Quận 1, Hồ Chí Minh',
      url:"https://destinationreporterindia.com/wp-content/uploads/2018/05/Ho-Chi-Minh-City2.jpg",
      openHours: '8:00 AM - 6:00 PM',
      phone: '02838221677',
      foundationYear: 1891,
      visitors: '80M',
      comments: "2.2K",
      rating: 4.4,
      des:"The Ho Chi Minh City Post Office, or the Saigon Central Post Office is a post office in the downtown Ho Chi Minh City, near Saigon Notre-Dame Basilica, the city's cathedral. The building was constructed when Vietnam was part of French Indochina in the late 19th century."
    },
  ];